In [1]:
import numpy as np
a = np.zeros((3, 3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
a[*[1,2]]

np.float64(0.0)

In [ ]:
a = AnotherEntity(store=GameStore(), name="Test Entity")

In [18]:

class State:
    machine: Machine

class Potato:
    def __init__(self):
        states=['idaho', 'not_idaho']
        transitions = [
            {'trigger': 'make_idaho', 'source': 'not_idaho', 'dest': 'idaho'},
            {'trigger': 'make_not_idaho', 'source': 'idaho', 'dest': 'not_idaho'}
        ]
        kind = State()
        kind.machine = Machine(model=kind, states=states, transitions=transitions, initial='not_idaho')
        self.kind = kind

        cook_states = ['raw', 'cooked', 'eaten']
        cook_transitions = [
            {'trigger': 'cook', 'source': 'raw', 'dest': 'cooked'},
            {'trigger': 'eat', 'source': 'cooked', 'dest': 'eaten', 'conditions':['is_idaho']}
        ]

        self.cook = State()
        self.cook.machine=Machine(model=a.cook, states=cook_states, transitions=cook_transitions, initial='raw')
    pass

a = Potato()


In [19]:
a.kind.make_idaho()

True

In [8]:
cook_states = ['raw', 'cooked', 'eaten']
cook_transitions = [
    {'trigger': 'cook', 'source': 'raw', 'dest': 'cooked'},
    {'trigger': 'eat', 'source': 'cooked', 'dest': 'eaten', 'conditions':['is_idaho']}
]

stove = Machine(model=a, states=cook_states, transitions=cook_transitions, initial='raw')
stove.set_state('raw')
a.cook()
a.eat() 


False

In [9]:
stove.set_state('raw')
a.make_idaho()


ValueError: State 'raw' is not a registered state.

In [ ]:
from core_components.entities.library import BaseGameEntity
from core_components.entities.types import *
from core_components.store import GameStore

In [ ]:
import os
os.getcwd()
os.chdir('c:/Users/jason/workspaces/repos/jrl/src')

from engine import GameEngine
from core_components.display import Display
from core_components.loop import GameLoop
from core_components.store import GameStore

game = GameEngine()
game.start()

In [ ]:
store.map

In [ ]:
game.state

In [ ]:

import type_protocols as tp
isinstance(game.display, tp.StateStoreObject)

In [ ]:
def get_stores(obj: object) -> list[tp.StateStoreObject]:
    found_stores = []
    for attribute in dir(obj):
        y = getattr(obj, attribute)
        if isinstance(y, tp.StateStoreObject):
            found_stores.append(y)
    return found_stores

stores = []
x = game.store

while get_stores(x):   
    new_stores = get_stores(x)
    for store in new_stores:
        print(store)
        x = store
        stores.append(x)

stores

In [ ]:
game.state, game.display.state, game.loop.state, game.store.state

In [ ]:
game.start()
game.state, game.display.state, game.loop.state, game.store.state

In [ ]:
game.play()
game.state, game.display.state, game.loop.state, game.store.state

In [ ]:
game.pause()
game.state, game.display.state, game.loop.state, game.store.state

In [ ]:
game.play()
game.state, game.display.state, game.loop.state, game.store.state

In [ ]:
game.reset()
game.state, game.display.state, game.loop.state, game.store.state

In [ ]:
game.stop()
game.state, game.display.state, game.loop.state, game.store.state


In [ ]:
test

In [ ]:
from type_protocols import StatefulObject
from core_components.loops import BaseLoopHandler, BaseGameEvent
from core_components.loop import GameLoop
from core_components.store import GameStore
import time
class NonEvent(BaseGameEvent):
    
    def trigger(self) -> None:
        print("Nothing happened.")
        super().trigger()

loop = GameLoop()
event = NonEvent()
event.store = GameStore()
event.transformer = loop.handler

loop.start()
event.trigger()
time.sleep(1)

loop.pause()
event.trigger()

loop.start()
event.trigger()
time.sleep(2)

In [ ]:
from core_components.store import GameStore

a = GameStore()
a.start()


In [ ]:
a.player

In [ ]:
from transitions import Machine

class Dummy:    
    def __init__(self):
        states = ['started', 'stopped']
        transitions =[
            {'trigger': 'start', 'source': 'stopped', 'dest': 'started'},
            {'trigger': 'stop', 'source': 'started', 'dest': 'stopped'}
            ]
        self.x = Machine(model=self, states=states, transitions=transitions, initial='stopped')

a = Dummy()
a.state

In [ ]:
a.state

In [ ]:
event = NonEvent()
event.store = GameStore()
event.transformer = loop.handler

loop.handler.events.put(event)

In [ ]:
event.trigger()

In [ ]:
loop.pause()
event.trigger()

In [ ]:
loop.start()

In [ ]:
loop.