In [ ]:

import numpy as np

from core_components.maps.base import grid_tile_dtype, ascii_graphic, GraphicTileMap, MapGraphics, DEFAULT_MANIFEST

tile_map = GraphicTileMap()

In [ ]:
a = np.array([[True, True],
              [True, False],
              [False, True],
              [False, False]])

dim1 = np.concatenate([a]*50).reshape(50, *a.shape)
dim2 = np.stack([dim1]*80, axis=0)
current_e = np.dstack([tile_map.tiles['visible']]*4).transpose(0, 2, 1).reshape(80, 50, 4, 1)
current_v = np.dstack([tile_map.tiles['explored']]*4).transpose(0, 2, 1).reshape(80, 50, 4, 1)
current = np.stack([current_e, current_v], axis=3).reshape(80, 50, 4, 2)
np.argwhere(np.all(current[:, :, :, :] == dim2[:, :, :, :], axis=(3,)))

# returns a mapping of state to label index

array([[ 0,  0,  3],
       [ 0,  1,  3],
       [ 0,  2,  3],
       ...,
       [79, 47,  3],
       [79, 48,  3],
       [79, 49,  3]], shape=(4000, 3))

In [309]:
dim1.shape

(50, 4, 2)

array([[[[ True,  True],
         [ True, False],
         [False,  True],
         [False, False]],

        [[ True,  True],
         [ True, False],
         [False,  True],
         [False, False]],

        [[ True,  True],
         [ True, False],
         [False,  True],
         [False, False]],

        ...,

        [[ True,  True],
         [ True, False],
         [False,  True],
         [False, False]],

        [[ True,  True],
         [ True, False],
         [False,  True],
         [False, False]],

        [[ True,  True],
         [ True, False],
         [False,  True],
         [False, False]]],


       [[[ True,  True],
         [ True, False],
         [False,  True],
         [False, False]],

        [[ True,  True],
         [ True, False],
         [False,  True],
         [False, False]],

        [[ True,  True],
         [ True, False],
         [False,  True],
         [False, False]],

        ...,

        [[ True,  True],
         [ True, False],
  

In [311]:
dim2.shape

(80, 50, 4, 2)

array([[ 0,  0,  2],
       [ 0,  1,  2],
       [ 0,  2,  2],
       ...,
       [79, 47,  2],
       [79, 48,  2],
       [79, 49,  2]], shape=(4000, 3))

array([[ 0,  0,  2],
       [ 0,  1,  2],
       [ 0,  2,  2],
       ...,
       [79, 47,  2],
       [79, 48,  2],
       [79, 49,  2]], shape=(4000, 3))

In [145]:
current_dim2 = np.dstack([current]*4).reshape(80, 50, 2, 4)
current_dim2[8:12, 8:12, 1, :]

array([[[ True, False,  True, False],
        [ True, False,  True, False],
        [ True, False,  True, False],
        [ True, False,  True, False]],

       [[ True, False,  True, False],
        [ True, False,  True, False],
        [ True, False,  True, False],
        [ True, False,  True, False]],

       [[ True, False,  True, False],
        [ True, False,  True, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True, False,  True, False],
        [ True, False,  True, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [66]:
state1 = np.array([True, True])
state2 = np.array([True, False])
state3 = np.array([False, True])
state4 = np.array([False, False])

states = np.vstack([state1, state2, state3, state4])
dim1 = np.concatenate([states]*50).reshape(50, *states.shape)
dim2 = np.concatenate([dim1]*80).reshape(80, 50, *states.shape)
dim2

array([[[[ True,  True],
         [ True, False],
         [False,  True],
         [False, False]],

        [[ True,  True],
         [ True, False],
         [False,  True],
         [False, False]],

        [[ True,  True],
         [ True, False],
         [False,  True],
         [False, False]],

        ...,

        [[ True,  True],
         [ True, False],
         [False,  True],
         [False, False]],

        [[ True,  True],
         [ True, False],
         [False,  True],
         [False, False]],

        [[ True,  True],
         [ True, False],
         [False,  True],
         [False, False]]],


       [[[ True,  True],
         [ True, False],
         [False,  True],
         [False, False]],

        [[ True,  True],
         [ True, False],
         [False,  True],
         [False, False]],

        [[ True,  True],
         [ True, False],
         [False,  True],
         [False, False]],

        ...,

        [[ True,  True],
         [ True, False],
  

In [ ]:
tile_map.tiles['graphic_type'][:]['name']



True

In [ ]:
for key in DEFAULT_GRAPHICS.keys():
    print(f"{key}: {DEFAULT_GRAPHICS[key] == tile_map._graphics_manifest[key]}")

In [ ]:
for key in tile_map._graphics_manifest['dtypes'].keys():
    print(f"{key}: {tile_map._graphics_manifest['dtypes'][key] == DEFAULT_GRAPHICS['dtypes'][key]}")

In [ ]:
DEFAULT_GRAPHICS['dtypes']

In [ ]:
tile_map._graphics_manifest['dtypes']

In [ ]:
area._align_center()
print(area.center)
area._align_corners()
print(area.top_left, area.bottom_right)

In [ ]:
import random
x,y =random.choice(np.argwhere(a))
int(x), int(y)

In [ ]:
def coordinate_overlap(dimension1: TileTuple, dimension2: TileTuple) -> bool:
    dim1_set1 = set(dimension1[0])
    dim1_set2 = set(dimension2[0])
    dim1_overlap = dim1_set1.is

    dim2_set1 = set(dimension1[1])
    dim2_set2 = set(dimension2[1])
    dim2_overlap = dim2_set1.isdisjoint(dim2_set2)
    
    return not (dim1_overlap or dim2_overlap)  

In [ ]:
a = set([1,2,3])
b = set([0,2])

b.issubset(a)

In [ ]:
a = np.full((5, 5), fill_value=False, dtype=bool)
a[mask_array] = True
a

In [ ]:
a &= mask_array
a

In [ ]:

dim1 = TileTuple((tiles[1][0].tolist()[1:3], tiles[1][0].tolist()[1:4]))
dim2 = TileTuple(([3,4], [3,4]))
coordinate_overlap(dim1, dim2)

In [ ]:
point1 = (1, 2)
point2 = (1, 3)


dim1 = ([point1[0]], [point1[1]])
dim2 = ([point2[0]], [point2[1]])

overlap(dim1, dim2)

In [ ]:
point1 = (0, 0)
point2 = (3, 4)
point3 = (4, 4)
point4 = (6, 8)


a = (range(point1[0], point2[0]), range(point1[1], point2[1]))
b = (range(point3[0], point4[0]), range(point3[1], point4[1]))

overlap(a, b)

In [ ]:
point1 = (1, 1)
point2 = (3, 3)
point3 = (4, 4)
point4 = (6, 6)

a = np.array([[1, 3], [1, 3]])  
b = np.array([[4, 6], [4, 6]])

overlap(a, b)

In [ ]:
point1 = (1, 1)
point2 = (3, 3)
point3 = (1, 1)
point4 = (3, 3)

a = np.array([[1, 3], [1, 3]])  
b = np.array([[1, 3], [1, 3]])

overlap(a, b)

In [ ]:
point1 = (1, 1)
point2 = (3, 5)
point3 = (4, 4)
point4 = (5, 5)

a = np.array([np.arange(1,4), np.arange(1,6)])  
b = np.array([np.arange(3, 6), np.arange(3, 6)])

overlap(a, b)

In [ ]:
from core_components.generators.random import GenericDungeonGenerator, CIRCULAR_ROOM_TEMPLATE
from core_components.tilemaps.base import MapCoords
import matplotlib.pyplot as plt
import numpy as np
dungeon_gen = GenericDungeonGenerator((50,50))
room_template = CIRCULAR_ROOM_TEMPLATE
center = MapCoords(15, 15)
size = (10, 8)

# Act
instance = dungeon_gen.generate()

In [ ]:
from core_components.tilemaps.base import MapCoords
a = MapCoords(14, 15)
b = MapCoords(14, 15)
a == b

In [ ]:

plt.imshow(instance.tiles['transparent'])

In [ ]:
dungeon_gen.corridors[0]

In [ ]:
plt.imshow(dungeon_gen.spawn_room(CIRCULAR_ROOM_TEMPLATE, center, size).inner_area)

In [ ]:
mask = np.full((width, height), False)
mask = np.s_[2:5, 2:5]

tile_map._tiles['type'][mask] = tile_map.resources['tiles']['floor']
tile_map._tiles[mask]['type']

In [ ]:
def istype(a: np.ndarray, dtype: np.dtype) -> bool:
    """Helper function to check if a numpy array is of a specific dtype"""
    if a.dtype.metadata is None or dtype.metadata is None:
        return False
    return a.dtype.metadata['__name__'] == dtype.metadata['__name__']

ascii_default = np.array((ord(' '), (255, 255, 255), (0, 0, 0)), dtype=ascii_graphic)

istype(ascii_default, ascii_graphic)  # True

In [ ]:
def run_tests(test_list):
    count = 0
    for test in test_list:
        try:
            test()
            count += 1
        except Exception as e:
            print(f"Exception: {test.__name__}: {e}")
            continue
    print(f"{count} of {len(test_list)} tests ran successfully.")

In [ ]:
from test.test_component_actions_system_dispatcher import *
tests = [test_dispatcher_ev_gamestart,
         test_dispatcher_ev_gameover,
         test_dispatcher_ev_keydown]

run_tests(tests)
# --- IGNORE ---

In [ ]:
from test.test_component_actions_dispatchers import *
tests = [test_dispatcher_ev_quit,
         test_dispatcher_initialization]

run_tests(tests)
# --- IGNORE ---

In [ ]:
from test.test_game_ai import *
test_game_over_event_handling()
test_game_ai_initialization()
test_game_ai_no_events()
test_game_ai_multiple_events()
test_game_ai_event_clearing()



In [ ]:
from test.test_game_map import *
test_get_map_coords()
test_in_bounds()
test_is_traversable_transparent_visible_explored()
test_out_of_bounds_checks()
test_set_visible_and_reset()
test_update_explored()
test_width_height()
test_tiles_initialization()


In [ ]:
from test.test_roster import *
test_roster_spawn()
test_roster_entity_blocked_locations()
test_roster_entity_collision()
test_roster_live_ai_actors()
test_roster_live_actors()
test_roster_get_entity_at_location()
